// General Conference talk library — extracted from the legacy EQ Planner.
// Doctrinal addresses only; procedural items omitted.
export const GC_TALKS = [
  { conf: "April 2026", session: "Saturday Morning", title: "About His Business", speaker: "Patrick Kearon" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/13kearon?lang=eng" },
  { conf: "April 2026", session: "Saturday Morning", title: "Ministering—“That Ye Love One Another; as I Have Loved You”", speaker: "Kristin M. Yee" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/14yee?lang=eng" },
  { conf: "April 2026", session: "Saturday Morning", title: "Come Home", speaker: "Clark G. Gilbert" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/15gilbert?lang=eng" },
  { conf: "April 2026", session: "Saturday Morning", title: "All Who Have Endured Valiantly", speaker: "David A. Bednar" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/16bednar?lang=eng" },
  { conf: "April 2026", session: "Saturday Morning", title: "Follow the Prophet; He Knows the Way", speaker: "Michael John U. Teh" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/17teh?lang=eng" },
  { conf: "April 2026", session: "Saturday Morning", title: "Tithing—Putting God First", speaker: "Jorge T. Becerra" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/18becerra?lang=eng" },
  { conf: "April 2026", session: "Saturday Morning", title: "Prayers for Peace", speaker: "Henry B. Eyring" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/19eyring?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "Lost Luggage, Redeemed Souls", speaker: "Gary E. Stevenson" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/23stevenson?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "Christ—Author and Finisher of Our Faith", speaker: "Eduardo F. Ortega" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/24ortega?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "“I Will Give Away All My Sins to Know Thee”", speaker: "Wan-Liang Wu" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/25wu?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "Jesus Christ Is Not Our Burden; He Is Our Relief", speaker: "David J. Wunderli" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/26wunderli?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "Love All; Love Each", speaker: "Gérald Caussé" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/27causse?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "Jesus Christ Is the Way", speaker: "Brian J. Holmes" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/28holmes?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "He Knows You by Name", speaker: "Clement M. Matswagothata" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/29matswagothata?lang=eng" },
  { conf: "April 2026", session: "Saturday Afternoon", title: "Jesus Christ—the True Vine", speaker: "Ulisses Soares" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/210soares?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "Encounter at the Empty Tomb", speaker: "Dieter F. Uchtdorf" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/41uchtdorf?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "Best Days and Worst Days", speaker: "Emily Belle Freeman" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/42freeman?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "I Feel My Savior’s Love", speaker: "Pedro X. Larreal" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/43larreal?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "Choose Jesus Christ as Your Guide", speaker: "Edward B. Rowe" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/44rowe?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "He Is Risen", speaker: "Ronald A. Rasband" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/45rasband?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "Because of Jesus Christ", speaker: "Dale G. Renlund" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/46renlund?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "The Joy of a Covenant Relationship with God", speaker: "Thierry K. Mutombo" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/47mutombo?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "A Peculiar Treasure", speaker: "Alan R. Walker" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/48walker?lang=eng" },
  { conf: "April 2026", session: "Sunday Morning", title: "Alive in Christ", speaker: "Dallin H. Oaks" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/49oaks?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "The Character of Christ", speaker: "D. Todd Christofferson" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/51christofferson?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "Remember, Remember", speaker: "Chi Hong (Sam) Wong" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/52wong?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "I Glory in My Jesus", speaker: "Aaron T. Hall" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/53hall?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "“Here Am I, Send Me”", speaker: "Susan H. Porter" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/54porter?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "Eternal Marriage Is an Eternal Journey", speaker: "Neil L. Andersen" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/55andersen?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "Keys, Covenants, and Easter", speaker: "Quentin L. Cook" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/56cook?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "Come unto Christ—Together", speaker: "Taniela B. Wakolo" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/57wakolo?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "’Tis Eastertide: No One Walks Alone", speaker: "Gerrit W. Gong" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/58gong?lang=eng" },
  { conf: "April 2026", session: "Sunday Afternoon", title: "Closing Remarks", speaker: "Dallin H. Oaks" , url: "https://www.churchofjesuschrist.org/study/general-conference/2026/04/59oaks?lang=eng" },
];
